/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAppSuaRouteImport } from './routes/_authenticated/app/sua'
import { Route as AuthenticatedAppResultadosRouteImport } from './routes/_authenticated/app/resultados'
import { Route as AuthenticatedAppPolizasRouteImport } from './routes/_authenticated/app/polizas'
import { Route as AuthenticatedAppNominaRouteImport } from './routes/_authenticated/app/nomina'
import { Route as AuthenticatedAppImportarLegacyRouteImport } from './routes/_authenticated/app/importar-legacy'
import { Route as AuthenticatedAppImportarRouteImport } from './routes/_authenticated/app/importar'
import { Route as AuthenticatedAppExportarRouteImport } from './routes/_authenticated/app/exportar'
import { Route as AuthenticatedAppEmpleadosRouteImport } from './routes/_authenticated/app/empleados'
import { Route as AuthenticatedAppDeclaracionesRouteImport } from './routes/_authenticated/app/declaraciones'
import { Route as AuthenticatedAppCuentasRouteImport } from './routes/_authenticated/app/cuentas'
import { Route as AuthenticatedAppConfiguracionRouteImport } from './routes/_authenticated/app/configuracion'
import { Route as AuthenticatedAppCobranzaRouteImport } from './routes/_authenticated/app/cobranza'
import { Route as AuthenticatedAppBalanzaRouteImport } from './routes/_authenticated/app/balanza'
import { Route as AuthenticatedAppBalanceRouteImport } from './routes/_authenticated/app/balance'
import { Route as AuthenticatedAppAsistenciasRouteImport } from './routes/_authenticated/app/asistencias'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminSolicitudesRouteImport } from './routes/_authenticated/admin/solicitudes'
import { Route as AuthenticatedAdminFacturapiRouteImport } from './routes/_authenticated/admin/facturapi'
import { Route as AuthenticatedAdminDeclaracionesRouteImport } from './routes/_authenticated/admin/declaraciones'
import { Route as AuthenticatedAdminConsumoRouteImport } from './routes/_authenticated/admin/consumo'
import { Route as AuthenticatedAdminCobranzaRouteImport } from './routes/_authenticated/admin/cobranza'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin/clientes'
import { Route as AuthenticatedAppSuaIndexRouteImport } from './routes/_authenticated/app/sua.index'
import { Route as AuthenticatedAppSuaPatronesRouteImport } from './routes/_authenticated/app/sua.patrones'
import { Route as AuthenticatedAppSuaPagosRouteImport } from './routes/_authenticated/app/sua.pagos'
import { Route as AuthenticatedAppSuaMovimientosRouteImport } from './routes/_authenticated/app/sua.movimientos'
import { Route as AuthenticatedAppSuaMensualesRouteImport } from './routes/_authenticated/app/sua.mensuales'
import { Route as AuthenticatedAppSuaImportarRouteImport } from './routes/_authenticated/app/sua.importar'
import { Route as AuthenticatedAppSuaBimestresRouteImport } from './routes/_authenticated/app/sua.bimestres'
import { Route as AuthenticatedAppFacturacionProductosRouteImport } from './routes/_authenticated/app/facturacion.productos'
import { Route as AuthenticatedAppFacturacionFacturasRouteImport } from './routes/_authenticated/app/facturacion.facturas'
import { Route as AuthenticatedAppFacturacionConfiguracionRouteImport } from './routes/_authenticated/app/facturacion.configuracion'
import { Route as AuthenticatedAppFacturacionComplementosRouteImport } from './routes/_authenticated/app/facturacion.complementos'
import { Route as AuthenticatedAppFacturacionClientesRouteImport } from './routes/_authenticated/app/facturacion.clientes'
import { Route as AuthenticatedAdminOrganizacionesOrgIdRouteImport } from './routes/_authenticated/admin/organizaciones.$orgId'
import { Route as AuthenticatedAdminClientesOrgIdRouteImport } from './routes/_authenticated/admin/clientes.$orgId'
import { Route as AuthenticatedAppSuaMensualesIndexRouteImport } from './routes/_authenticated/app/sua.mensuales.index'
import { Route as AuthenticatedAppSuaBimestresIndexRouteImport } from './routes/_authenticated/app/sua.bimestres.index'
import { Route as AuthenticatedAppSuaMensualesIdRouteImport } from './routes/_authenticated/app/sua.mensuales.$id'
import { Route as AuthenticatedAppSuaBimestresIdRouteImport } from './routes/_authenticated/app/sua.bimestres.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAppSuaRoute = AuthenticatedAppSuaRouteImport.update({
  id: '/app/sua',
  path: '/app/sua',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppResultadosRoute =
  AuthenticatedAppResultadosRouteImport.update({
    id: '/app/resultados',
    path: '/app/resultados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPolizasRoute = AuthenticatedAppPolizasRouteImport.update({
  id: '/app/polizas',
  path: '/app/polizas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppNominaRoute = AuthenticatedAppNominaRouteImport.update({
  id: '/app/nomina',
  path: '/app/nomina',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppImportarLegacyRoute =
  AuthenticatedAppImportarLegacyRouteImport.update({
    id: '/app/importar-legacy',
    path: '/app/importar-legacy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppImportarRoute =
  AuthenticatedAppImportarRouteImport.update({
    id: '/app/importar',
    path: '/app/importar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppExportarRoute =
  AuthenticatedAppExportarRouteImport.update({
    id: '/app/exportar',
    path: '/app/exportar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppEmpleadosRoute =
  AuthenticatedAppEmpleadosRouteImport.update({
    id: '/app/empleados',
    path: '/app/empleados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDeclaracionesRoute =
  AuthenticatedAppDeclaracionesRouteImport.update({
    id: '/app/declaraciones',
    path: '/app/declaraciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCuentasRoute = AuthenticatedAppCuentasRouteImport.update({
  id: '/app/cuentas',
  path: '/app/cuentas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppConfiguracionRoute =
  AuthenticatedAppConfiguracionRouteImport.update({
    id: '/app/configuracion',
    path: '/app/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCobranzaRoute =
  AuthenticatedAppCobranzaRouteImport.update({
    id: '/app/cobranza',
    path: '/app/cobranza',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBalanzaRoute = AuthenticatedAppBalanzaRouteImport.update({
  id: '/app/balanza',
  path: '/app/balanza',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppBalanceRoute = AuthenticatedAppBalanceRouteImport.update({
  id: '/app/balance',
  path: '/app/balance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAsistenciasRoute =
  AuthenticatedAppAsistenciasRouteImport.update({
    id: '/app/asistencias',
    path: '/app/asistencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSolicitudesRoute =
  AuthenticatedAdminSolicitudesRouteImport.update({
    id: '/solicitudes',
    path: '/solicitudes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFacturapiRoute =
  AuthenticatedAdminFacturapiRouteImport.update({
    id: '/facturapi',
    path: '/facturapi',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDeclaracionesRoute =
  AuthenticatedAdminDeclaracionesRouteImport.update({
    id: '/declaraciones',
    path: '/declaraciones',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConsumoRoute =
  AuthenticatedAdminConsumoRouteImport.update({
    id: '/consumo',
    path: '/consumo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCobranzaRoute =
  AuthenticatedAdminCobranzaRouteImport.update({
    id: '/cobranza',
    path: '/cobranza',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppSuaIndexRoute =
  AuthenticatedAppSuaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppSuaRoute,
  } as any)
const AuthenticatedAppSuaPatronesRoute =
  AuthenticatedAppSuaPatronesRouteImport.update({
    id: '/patrones',
    path: '/patrones',
    getParentRoute: () => AuthenticatedAppSuaRoute,
  } as any)
const AuthenticatedAppSuaPagosRoute =
  AuthenticatedAppSuaPagosRouteImport.update({
    id: '/pagos',
    path: '/pagos',
    getParentRoute: () => AuthenticatedAppSuaRoute,
  } as any)
const AuthenticatedAppSuaMovimientosRoute =
  AuthenticatedAppSuaMovimientosRouteImport.update({
    id: '/movimientos',
    path: '/movimientos',
    getParentRoute: () => AuthenticatedAppSuaRoute,
  } as any)
const AuthenticatedAppSuaMensualesRoute =
  AuthenticatedAppSuaMensualesRouteImport.update({
    id: '/mensuales',
    path: '/mensuales',
    getParentRoute: () => AuthenticatedAppSuaRoute,
  } as any)
const AuthenticatedAppSuaImportarRoute =
  AuthenticatedAppSuaImportarRouteImport.update({
    id: '/importar',
    path: '/importar',
    getParentRoute: () => AuthenticatedAppSuaRoute,
  } as any)
const AuthenticatedAppSuaBimestresRoute =
  AuthenticatedAppSuaBimestresRouteImport.update({
    id: '/bimestres',
    path: '/bimestres',
    getParentRoute: () => AuthenticatedAppSuaRoute,
  } as any)
const AuthenticatedAppFacturacionProductosRoute =
  AuthenticatedAppFacturacionProductosRouteImport.update({
    id: '/app/facturacion/productos',
    path: '/app/facturacion/productos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFacturacionFacturasRoute =
  AuthenticatedAppFacturacionFacturasRouteImport.update({
    id: '/app/facturacion/facturas',
    path: '/app/facturacion/facturas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFacturacionConfiguracionRoute =
  AuthenticatedAppFacturacionConfiguracionRouteImport.update({
    id: '/app/facturacion/configuracion',
    path: '/app/facturacion/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFacturacionComplementosRoute =
  AuthenticatedAppFacturacionComplementosRouteImport.update({
    id: '/app/facturacion/complementos',
    path: '/app/facturacion/complementos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFacturacionClientesRoute =
  AuthenticatedAppFacturacionClientesRouteImport.update({
    id: '/app/facturacion/clientes',
    path: '/app/facturacion/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrganizacionesOrgIdRoute =
  AuthenticatedAdminOrganizacionesOrgIdRouteImport.update({
    id: '/organizaciones/$orgId',
    path: '/organizaciones/$orgId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientesOrgIdRoute =
  AuthenticatedAdminClientesOrgIdRouteImport.update({
    id: '/$orgId',
    path: '/$orgId',
    getParentRoute: () => AuthenticatedAdminClientesRoute,
  } as any)
const AuthenticatedAppSuaMensualesIndexRoute =
  AuthenticatedAppSuaMensualesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppSuaMensualesRoute,
  } as any)
const AuthenticatedAppSuaBimestresIndexRoute =
  AuthenticatedAppSuaBimestresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppSuaBimestresRoute,
  } as any)
const AuthenticatedAppSuaMensualesIdRoute =
  AuthenticatedAppSuaMensualesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppSuaMensualesRoute,
  } as any)
const AuthenticatedAppSuaBimestresIdRoute =
  AuthenticatedAppSuaBimestresIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppSuaBimestresRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRouteWithChildren
  '/admin/cobranza': typeof AuthenticatedAdminCobranzaRoute
  '/admin/consumo': typeof AuthenticatedAdminConsumoRoute
  '/admin/declaraciones': typeof AuthenticatedAdminDeclaracionesRoute
  '/admin/facturapi': typeof AuthenticatedAdminFacturapiRoute
  '/admin/solicitudes': typeof AuthenticatedAdminSolicitudesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/app/asistencias': typeof AuthenticatedAppAsistenciasRoute
  '/app/balance': typeof AuthenticatedAppBalanceRoute
  '/app/balanza': typeof AuthenticatedAppBalanzaRoute
  '/app/cobranza': typeof AuthenticatedAppCobranzaRoute
  '/app/configuracion': typeof AuthenticatedAppConfiguracionRoute
  '/app/cuentas': typeof AuthenticatedAppCuentasRoute
  '/app/declaraciones': typeof AuthenticatedAppDeclaracionesRoute
  '/app/empleados': typeof AuthenticatedAppEmpleadosRoute
  '/app/exportar': typeof AuthenticatedAppExportarRoute
  '/app/importar': typeof AuthenticatedAppImportarRoute
  '/app/importar-legacy': typeof AuthenticatedAppImportarLegacyRoute
  '/app/nomina': typeof AuthenticatedAppNominaRoute
  '/app/polizas': typeof AuthenticatedAppPolizasRoute
  '/app/resultados': typeof AuthenticatedAppResultadosRoute
  '/app/sua': typeof AuthenticatedAppSuaRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/clientes/$orgId': typeof AuthenticatedAdminClientesOrgIdRoute
  '/admin/organizaciones/$orgId': typeof AuthenticatedAdminOrganizacionesOrgIdRoute
  '/app/facturacion/clientes': typeof AuthenticatedAppFacturacionClientesRoute
  '/app/facturacion/complementos': typeof AuthenticatedAppFacturacionComplementosRoute
  '/app/facturacion/configuracion': typeof AuthenticatedAppFacturacionConfiguracionRoute
  '/app/facturacion/facturas': typeof AuthenticatedAppFacturacionFacturasRoute
  '/app/facturacion/productos': typeof AuthenticatedAppFacturacionProductosRoute
  '/app/sua/bimestres': typeof AuthenticatedAppSuaBimestresRouteWithChildren
  '/app/sua/importar': typeof AuthenticatedAppSuaImportarRoute
  '/app/sua/mensuales': typeof AuthenticatedAppSuaMensualesRouteWithChildren
  '/app/sua/movimientos': typeof AuthenticatedAppSuaMovimientosRoute
  '/app/sua/pagos': typeof AuthenticatedAppSuaPagosRoute
  '/app/sua/patrones': typeof AuthenticatedAppSuaPatronesRoute
  '/app/sua/': typeof AuthenticatedAppSuaIndexRoute
  '/app/sua/bimestres/$id': typeof AuthenticatedAppSuaBimestresIdRoute
  '/app/sua/mensuales/$id': typeof AuthenticatedAppSuaMensualesIdRoute
  '/app/sua/bimestres/': typeof AuthenticatedAppSuaBimestresIndexRoute
  '/app/sua/mensuales/': typeof AuthenticatedAppSuaMensualesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRouteWithChildren
  '/admin/cobranza': typeof AuthenticatedAdminCobranzaRoute
  '/admin/consumo': typeof AuthenticatedAdminConsumoRoute
  '/admin/declaraciones': typeof AuthenticatedAdminDeclaracionesRoute
  '/admin/facturapi': typeof AuthenticatedAdminFacturapiRoute
  '/admin/solicitudes': typeof AuthenticatedAdminSolicitudesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/app/asistencias': typeof AuthenticatedAppAsistenciasRoute
  '/app/balance': typeof AuthenticatedAppBalanceRoute
  '/app/balanza': typeof AuthenticatedAppBalanzaRoute
  '/app/cobranza': typeof AuthenticatedAppCobranzaRoute
  '/app/configuracion': typeof AuthenticatedAppConfiguracionRoute
  '/app/cuentas': typeof AuthenticatedAppCuentasRoute
  '/app/declaraciones': typeof AuthenticatedAppDeclaracionesRoute
  '/app/empleados': typeof AuthenticatedAppEmpleadosRoute
  '/app/exportar': typeof AuthenticatedAppExportarRoute
  '/app/importar': typeof AuthenticatedAppImportarRoute
  '/app/importar-legacy': typeof AuthenticatedAppImportarLegacyRoute
  '/app/nomina': typeof AuthenticatedAppNominaRoute
  '/app/polizas': typeof AuthenticatedAppPolizasRoute
  '/app/resultados': typeof AuthenticatedAppResultadosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin/clientes/$orgId': typeof AuthenticatedAdminClientesOrgIdRoute
  '/admin/organizaciones/$orgId': typeof AuthenticatedAdminOrganizacionesOrgIdRoute
  '/app/facturacion/clientes': typeof AuthenticatedAppFacturacionClientesRoute
  '/app/facturacion/complementos': typeof AuthenticatedAppFacturacionComplementosRoute
  '/app/facturacion/configuracion': typeof AuthenticatedAppFacturacionConfiguracionRoute
  '/app/facturacion/facturas': typeof AuthenticatedAppFacturacionFacturasRoute
  '/app/facturacion/productos': typeof AuthenticatedAppFacturacionProductosRoute
  '/app/sua/importar': typeof AuthenticatedAppSuaImportarRoute
  '/app/sua/movimientos': typeof AuthenticatedAppSuaMovimientosRoute
  '/app/sua/pagos': typeof AuthenticatedAppSuaPagosRoute
  '/app/sua/patrones': typeof AuthenticatedAppSuaPatronesRoute
  '/app/sua': typeof AuthenticatedAppSuaIndexRoute
  '/app/sua/bimestres/$id': typeof AuthenticatedAppSuaBimestresIdRoute
  '/app/sua/mensuales/$id': typeof AuthenticatedAppSuaMensualesIdRoute
  '/app/sua/bimestres': typeof AuthenticatedAppSuaBimestresIndexRoute
  '/app/sua/mensuales': typeof AuthenticatedAppSuaMensualesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRouteWithChildren
  '/_authenticated/admin/cobranza': typeof AuthenticatedAdminCobranzaRoute
  '/_authenticated/admin/consumo': typeof AuthenticatedAdminConsumoRoute
  '/_authenticated/admin/declaraciones': typeof AuthenticatedAdminDeclaracionesRoute
  '/_authenticated/admin/facturapi': typeof AuthenticatedAdminFacturapiRoute
  '/_authenticated/admin/solicitudes': typeof AuthenticatedAdminSolicitudesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/app/asistencias': typeof AuthenticatedAppAsistenciasRoute
  '/_authenticated/app/balance': typeof AuthenticatedAppBalanceRoute
  '/_authenticated/app/balanza': typeof AuthenticatedAppBalanzaRoute
  '/_authenticated/app/cobranza': typeof AuthenticatedAppCobranzaRoute
  '/_authenticated/app/configuracion': typeof AuthenticatedAppConfiguracionRoute
  '/_authenticated/app/cuentas': typeof AuthenticatedAppCuentasRoute
  '/_authenticated/app/declaraciones': typeof AuthenticatedAppDeclaracionesRoute
  '/_authenticated/app/empleados': typeof AuthenticatedAppEmpleadosRoute
  '/_authenticated/app/exportar': typeof AuthenticatedAppExportarRoute
  '/_authenticated/app/importar': typeof AuthenticatedAppImportarRoute
  '/_authenticated/app/importar-legacy': typeof AuthenticatedAppImportarLegacyRoute
  '/_authenticated/app/nomina': typeof AuthenticatedAppNominaRoute
  '/_authenticated/app/polizas': typeof AuthenticatedAppPolizasRoute
  '/_authenticated/app/resultados': typeof AuthenticatedAppResultadosRoute
  '/_authenticated/app/sua': typeof AuthenticatedAppSuaRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/admin/clientes/$orgId': typeof AuthenticatedAdminClientesOrgIdRoute
  '/_authenticated/admin/organizaciones/$orgId': typeof AuthenticatedAdminOrganizacionesOrgIdRoute
  '/_authenticated/app/facturacion/clientes': typeof AuthenticatedAppFacturacionClientesRoute
  '/_authenticated/app/facturacion/complementos': typeof AuthenticatedAppFacturacionComplementosRoute
  '/_authenticated/app/facturacion/configuracion': typeof AuthenticatedAppFacturacionConfiguracionRoute
  '/_authenticated/app/facturacion/facturas': typeof AuthenticatedAppFacturacionFacturasRoute
  '/_authenticated/app/facturacion/productos': typeof AuthenticatedAppFacturacionProductosRoute
  '/_authenticated/app/sua/bimestres': typeof AuthenticatedAppSuaBimestresRouteWithChildren
  '/_authenticated/app/sua/importar': typeof AuthenticatedAppSuaImportarRoute
  '/_authenticated/app/sua/mensuales': typeof AuthenticatedAppSuaMensualesRouteWithChildren
  '/_authenticated/app/sua/movimientos': typeof AuthenticatedAppSuaMovimientosRoute
  '/_authenticated/app/sua/pagos': typeof AuthenticatedAppSuaPagosRoute
  '/_authenticated/app/sua/patrones': typeof AuthenticatedAppSuaPatronesRoute
  '/_authenticated/app/sua/': typeof AuthenticatedAppSuaIndexRoute
  '/_authenticated/app/sua/bimestres/$id': typeof AuthenticatedAppSuaBimestresIdRoute
  '/_authenticated/app/sua/mensuales/$id': typeof AuthenticatedAppSuaMensualesIdRoute
  '/_authenticated/app/sua/bimestres/': typeof AuthenticatedAppSuaBimestresIndexRoute
  '/_authenticated/app/sua/mensuales/': typeof AuthenticatedAppSuaMensualesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/onboarding'
    | '/admin/clientes'
    | '/admin/cobranza'
    | '/admin/consumo'
    | '/admin/declaraciones'
    | '/admin/facturapi'
    | '/admin/solicitudes'
    | '/admin/usuarios'
    | '/app/asistencias'
    | '/app/balance'
    | '/app/balanza'
    | '/app/cobranza'
    | '/app/configuracion'
    | '/app/cuentas'
    | '/app/declaraciones'
    | '/app/empleados'
    | '/app/exportar'
    | '/app/importar'
    | '/app/importar-legacy'
    | '/app/nomina'
    | '/app/polizas'
    | '/app/resultados'
    | '/app/sua'
    | '/admin/'
    | '/app/'
    | '/admin/clientes/$orgId'
    | '/admin/organizaciones/$orgId'
    | '/app/facturacion/clientes'
    | '/app/facturacion/complementos'
    | '/app/facturacion/configuracion'
    | '/app/facturacion/facturas'
    | '/app/facturacion/productos'
    | '/app/sua/bimestres'
    | '/app/sua/importar'
    | '/app/sua/mensuales'
    | '/app/sua/movimientos'
    | '/app/sua/pagos'
    | '/app/sua/patrones'
    | '/app/sua/'
    | '/app/sua/bimestres/$id'
    | '/app/sua/mensuales/$id'
    | '/app/sua/bimestres/'
    | '/app/sua/mensuales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin/clientes'
    | '/admin/cobranza'
    | '/admin/consumo'
    | '/admin/declaraciones'
    | '/admin/facturapi'
    | '/admin/solicitudes'
    | '/admin/usuarios'
    | '/app/asistencias'
    | '/app/balance'
    | '/app/balanza'
    | '/app/cobranza'
    | '/app/configuracion'
    | '/app/cuentas'
    | '/app/declaraciones'
    | '/app/empleados'
    | '/app/exportar'
    | '/app/importar'
    | '/app/importar-legacy'
    | '/app/nomina'
    | '/app/polizas'
    | '/app/resultados'
    | '/admin'
    | '/app'
    | '/admin/clientes/$orgId'
    | '/admin/organizaciones/$orgId'
    | '/app/facturacion/clientes'
    | '/app/facturacion/complementos'
    | '/app/facturacion/configuracion'
    | '/app/facturacion/facturas'
    | '/app/facturacion/productos'
    | '/app/sua/importar'
    | '/app/sua/movimientos'
    | '/app/sua/pagos'
    | '/app/sua/patrones'
    | '/app/sua'
    | '/app/sua/bimestres/$id'
    | '/app/sua/mensuales/$id'
    | '/app/sua/bimestres'
    | '/app/sua/mensuales'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/onboarding'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/cobranza'
    | '/_authenticated/admin/consumo'
    | '/_authenticated/admin/declaraciones'
    | '/_authenticated/admin/facturapi'
    | '/_authenticated/admin/solicitudes'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/app/asistencias'
    | '/_authenticated/app/balance'
    | '/_authenticated/app/balanza'
    | '/_authenticated/app/cobranza'
    | '/_authenticated/app/configuracion'
    | '/_authenticated/app/cuentas'
    | '/_authenticated/app/declaraciones'
    | '/_authenticated/app/empleados'
    | '/_authenticated/app/exportar'
    | '/_authenticated/app/importar'
    | '/_authenticated/app/importar-legacy'
    | '/_authenticated/app/nomina'
    | '/_authenticated/app/polizas'
    | '/_authenticated/app/resultados'
    | '/_authenticated/app/sua'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/admin/clientes/$orgId'
    | '/_authenticated/admin/organizaciones/$orgId'
    | '/_authenticated/app/facturacion/clientes'
    | '/_authenticated/app/facturacion/complementos'
    | '/_authenticated/app/facturacion/configuracion'
    | '/_authenticated/app/facturacion/facturas'
    | '/_authenticated/app/facturacion/productos'
    | '/_authenticated/app/sua/bimestres'
    | '/_authenticated/app/sua/importar'
    | '/_authenticated/app/sua/mensuales'
    | '/_authenticated/app/sua/movimientos'
    | '/_authenticated/app/sua/pagos'
    | '/_authenticated/app/sua/patrones'
    | '/_authenticated/app/sua/'
    | '/_authenticated/app/sua/bimestres/$id'
    | '/_authenticated/app/sua/mensuales/$id'
    | '/_authenticated/app/sua/bimestres/'
    | '/_authenticated/app/sua/mensuales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/app/sua': {
      id: '/_authenticated/app/sua'
      path: '/app/sua'
      fullPath: '/app/sua'
      preLoaderRoute: typeof AuthenticatedAppSuaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/resultados': {
      id: '/_authenticated/app/resultados'
      path: '/app/resultados'
      fullPath: '/app/resultados'
      preLoaderRoute: typeof AuthenticatedAppResultadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/polizas': {
      id: '/_authenticated/app/polizas'
      path: '/app/polizas'
      fullPath: '/app/polizas'
      preLoaderRoute: typeof AuthenticatedAppPolizasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/nomina': {
      id: '/_authenticated/app/nomina'
      path: '/app/nomina'
      fullPath: '/app/nomina'
      preLoaderRoute: typeof AuthenticatedAppNominaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/importar-legacy': {
      id: '/_authenticated/app/importar-legacy'
      path: '/app/importar-legacy'
      fullPath: '/app/importar-legacy'
      preLoaderRoute: typeof AuthenticatedAppImportarLegacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/importar': {
      id: '/_authenticated/app/importar'
      path: '/app/importar'
      fullPath: '/app/importar'
      preLoaderRoute: typeof AuthenticatedAppImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/exportar': {
      id: '/_authenticated/app/exportar'
      path: '/app/exportar'
      fullPath: '/app/exportar'
      preLoaderRoute: typeof AuthenticatedAppExportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/empleados': {
      id: '/_authenticated/app/empleados'
      path: '/app/empleados'
      fullPath: '/app/empleados'
      preLoaderRoute: typeof AuthenticatedAppEmpleadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/declaraciones': {
      id: '/_authenticated/app/declaraciones'
      path: '/app/declaraciones'
      fullPath: '/app/declaraciones'
      preLoaderRoute: typeof AuthenticatedAppDeclaracionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/cuentas': {
      id: '/_authenticated/app/cuentas'
      path: '/app/cuentas'
      fullPath: '/app/cuentas'
      preLoaderRoute: typeof AuthenticatedAppCuentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/configuracion': {
      id: '/_authenticated/app/configuracion'
      path: '/app/configuracion'
      fullPath: '/app/configuracion'
      preLoaderRoute: typeof AuthenticatedAppConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/cobranza': {
      id: '/_authenticated/app/cobranza'
      path: '/app/cobranza'
      fullPath: '/app/cobranza'
      preLoaderRoute: typeof AuthenticatedAppCobranzaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/balanza': {
      id: '/_authenticated/app/balanza'
      path: '/app/balanza'
      fullPath: '/app/balanza'
      preLoaderRoute: typeof AuthenticatedAppBalanzaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/balance': {
      id: '/_authenticated/app/balance'
      path: '/app/balance'
      fullPath: '/app/balance'
      preLoaderRoute: typeof AuthenticatedAppBalanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/asistencias': {
      id: '/_authenticated/app/asistencias'
      path: '/app/asistencias'
      fullPath: '/app/asistencias'
      preLoaderRoute: typeof AuthenticatedAppAsistenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/solicitudes': {
      id: '/_authenticated/admin/solicitudes'
      path: '/solicitudes'
      fullPath: '/admin/solicitudes'
      preLoaderRoute: typeof AuthenticatedAdminSolicitudesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/facturapi': {
      id: '/_authenticated/admin/facturapi'
      path: '/facturapi'
      fullPath: '/admin/facturapi'
      preLoaderRoute: typeof AuthenticatedAdminFacturapiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/declaraciones': {
      id: '/_authenticated/admin/declaraciones'
      path: '/declaraciones'
      fullPath: '/admin/declaraciones'
      preLoaderRoute: typeof AuthenticatedAdminDeclaracionesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/consumo': {
      id: '/_authenticated/admin/consumo'
      path: '/consumo'
      fullPath: '/admin/consumo'
      preLoaderRoute: typeof AuthenticatedAdminConsumoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cobranza': {
      id: '/_authenticated/admin/cobranza'
      path: '/cobranza'
      fullPath: '/admin/cobranza'
      preLoaderRoute: typeof AuthenticatedAdminCobranzaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/app/sua/': {
      id: '/_authenticated/app/sua/'
      path: '/'
      fullPath: '/app/sua/'
      preLoaderRoute: typeof AuthenticatedAppSuaIndexRouteImport
      parentRoute: typeof AuthenticatedAppSuaRoute
    }
    '/_authenticated/app/sua/patrones': {
      id: '/_authenticated/app/sua/patrones'
      path: '/patrones'
      fullPath: '/app/sua/patrones'
      preLoaderRoute: typeof AuthenticatedAppSuaPatronesRouteImport
      parentRoute: typeof AuthenticatedAppSuaRoute
    }
    '/_authenticated/app/sua/pagos': {
      id: '/_authenticated/app/sua/pagos'
      path: '/pagos'
      fullPath: '/app/sua/pagos'
      preLoaderRoute: typeof AuthenticatedAppSuaPagosRouteImport
      parentRoute: typeof AuthenticatedAppSuaRoute
    }
    '/_authenticated/app/sua/movimientos': {
      id: '/_authenticated/app/sua/movimientos'
      path: '/movimientos'
      fullPath: '/app/sua/movimientos'
      preLoaderRoute: typeof AuthenticatedAppSuaMovimientosRouteImport
      parentRoute: typeof AuthenticatedAppSuaRoute
    }
    '/_authenticated/app/sua/mensuales': {
      id: '/_authenticated/app/sua/mensuales'
      path: '/mensuales'
      fullPath: '/app/sua/mensuales'
      preLoaderRoute: typeof AuthenticatedAppSuaMensualesRouteImport
      parentRoute: typeof AuthenticatedAppSuaRoute
    }
    '/_authenticated/app/sua/importar': {
      id: '/_authenticated/app/sua/importar'
      path: '/importar'
      fullPath: '/app/sua/importar'
      preLoaderRoute: typeof AuthenticatedAppSuaImportarRouteImport
      parentRoute: typeof AuthenticatedAppSuaRoute
    }
    '/_authenticated/app/sua/bimestres': {
      id: '/_authenticated/app/sua/bimestres'
      path: '/bimestres'
      fullPath: '/app/sua/bimestres'
      preLoaderRoute: typeof AuthenticatedAppSuaBimestresRouteImport
      parentRoute: typeof AuthenticatedAppSuaRoute
    }
    '/_authenticated/app/facturacion/productos': {
      id: '/_authenticated/app/facturacion/productos'
      path: '/app/facturacion/productos'
      fullPath: '/app/facturacion/productos'
      preLoaderRoute: typeof AuthenticatedAppFacturacionProductosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/facturacion/facturas': {
      id: '/_authenticated/app/facturacion/facturas'
      path: '/app/facturacion/facturas'
      fullPath: '/app/facturacion/facturas'
      preLoaderRoute: typeof AuthenticatedAppFacturacionFacturasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/facturacion/configuracion': {
      id: '/_authenticated/app/facturacion/configuracion'
      path: '/app/facturacion/configuracion'
      fullPath: '/app/facturacion/configuracion'
      preLoaderRoute: typeof AuthenticatedAppFacturacionConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/facturacion/complementos': {
      id: '/_authenticated/app/facturacion/complementos'
      path: '/app/facturacion/complementos'
      fullPath: '/app/facturacion/complementos'
      preLoaderRoute: typeof AuthenticatedAppFacturacionComplementosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/facturacion/clientes': {
      id: '/_authenticated/app/facturacion/clientes'
      path: '/app/facturacion/clientes'
      fullPath: '/app/facturacion/clientes'
      preLoaderRoute: typeof AuthenticatedAppFacturacionClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/organizaciones/$orgId': {
      id: '/_authenticated/admin/organizaciones/$orgId'
      path: '/organizaciones/$orgId'
      fullPath: '/admin/organizaciones/$orgId'
      preLoaderRoute: typeof AuthenticatedAdminOrganizacionesOrgIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clientes/$orgId': {
      id: '/_authenticated/admin/clientes/$orgId'
      path: '/$orgId'
      fullPath: '/admin/clientes/$orgId'
      preLoaderRoute: typeof AuthenticatedAdminClientesOrgIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientesRoute
    }
    '/_authenticated/app/sua/mensuales/': {
      id: '/_authenticated/app/sua/mensuales/'
      path: '/'
      fullPath: '/app/sua/mensuales/'
      preLoaderRoute: typeof AuthenticatedAppSuaMensualesIndexRouteImport
      parentRoute: typeof AuthenticatedAppSuaMensualesRoute
    }
    '/_authenticated/app/sua/bimestres/': {
      id: '/_authenticated/app/sua/bimestres/'
      path: '/'
      fullPath: '/app/sua/bimestres/'
      preLoaderRoute: typeof AuthenticatedAppSuaBimestresIndexRouteImport
      parentRoute: typeof AuthenticatedAppSuaBimestresRoute
    }
    '/_authenticated/app/sua/mensuales/$id': {
      id: '/_authenticated/app/sua/mensuales/$id'
      path: '/$id'
      fullPath: '/app/sua/mensuales/$id'
      preLoaderRoute: typeof AuthenticatedAppSuaMensualesIdRouteImport
      parentRoute: typeof AuthenticatedAppSuaMensualesRoute
    }
    '/_authenticated/app/sua/bimestres/$id': {
      id: '/_authenticated/app/sua/bimestres/$id'
      path: '/$id'
      fullPath: '/app/sua/bimestres/$id'
      preLoaderRoute: typeof AuthenticatedAppSuaBimestresIdRouteImport
      parentRoute: typeof AuthenticatedAppSuaBimestresRoute
    }
  }
}

interface AuthenticatedAdminClientesRouteChildren {
  AuthenticatedAdminClientesOrgIdRoute: typeof AuthenticatedAdminClientesOrgIdRoute
}

const AuthenticatedAdminClientesRouteChildren: AuthenticatedAdminClientesRouteChildren =
  {
    AuthenticatedAdminClientesOrgIdRoute: AuthenticatedAdminClientesOrgIdRoute,
  }

const AuthenticatedAdminClientesRouteWithChildren =
  AuthenticatedAdminClientesRoute._addFileChildren(
    AuthenticatedAdminClientesRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRouteWithChildren
  AuthenticatedAdminCobranzaRoute: typeof AuthenticatedAdminCobranzaRoute
  AuthenticatedAdminConsumoRoute: typeof AuthenticatedAdminConsumoRoute
  AuthenticatedAdminDeclaracionesRoute: typeof AuthenticatedAdminDeclaracionesRoute
  AuthenticatedAdminFacturapiRoute: typeof AuthenticatedAdminFacturapiRoute
  AuthenticatedAdminSolicitudesRoute: typeof AuthenticatedAdminSolicitudesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminOrganizacionesOrgIdRoute: typeof AuthenticatedAdminOrganizacionesOrgIdRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminClientesRoute:
      AuthenticatedAdminClientesRouteWithChildren,
    AuthenticatedAdminCobranzaRoute: AuthenticatedAdminCobranzaRoute,
    AuthenticatedAdminConsumoRoute: AuthenticatedAdminConsumoRoute,
    AuthenticatedAdminDeclaracionesRoute: AuthenticatedAdminDeclaracionesRoute,
    AuthenticatedAdminFacturapiRoute: AuthenticatedAdminFacturapiRoute,
    AuthenticatedAdminSolicitudesRoute: AuthenticatedAdminSolicitudesRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminOrganizacionesOrgIdRoute:
      AuthenticatedAdminOrganizacionesOrgIdRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAppSuaBimestresRouteChildren {
  AuthenticatedAppSuaBimestresIdRoute: typeof AuthenticatedAppSuaBimestresIdRoute
  AuthenticatedAppSuaBimestresIndexRoute: typeof AuthenticatedAppSuaBimestresIndexRoute
}

const AuthenticatedAppSuaBimestresRouteChildren: AuthenticatedAppSuaBimestresRouteChildren =
  {
    AuthenticatedAppSuaBimestresIdRoute: AuthenticatedAppSuaBimestresIdRoute,
    AuthenticatedAppSuaBimestresIndexRoute:
      AuthenticatedAppSuaBimestresIndexRoute,
  }

const AuthenticatedAppSuaBimestresRouteWithChildren =
  AuthenticatedAppSuaBimestresRoute._addFileChildren(
    AuthenticatedAppSuaBimestresRouteChildren,
  )

interface AuthenticatedAppSuaMensualesRouteChildren {
  AuthenticatedAppSuaMensualesIdRoute: typeof AuthenticatedAppSuaMensualesIdRoute
  AuthenticatedAppSuaMensualesIndexRoute: typeof AuthenticatedAppSuaMensualesIndexRoute
}

const AuthenticatedAppSuaMensualesRouteChildren: AuthenticatedAppSuaMensualesRouteChildren =
  {
    AuthenticatedAppSuaMensualesIdRoute: AuthenticatedAppSuaMensualesIdRoute,
    AuthenticatedAppSuaMensualesIndexRoute:
      AuthenticatedAppSuaMensualesIndexRoute,
  }

const AuthenticatedAppSuaMensualesRouteWithChildren =
  AuthenticatedAppSuaMensualesRoute._addFileChildren(
    AuthenticatedAppSuaMensualesRouteChildren,
  )

interface AuthenticatedAppSuaRouteChildren {
  AuthenticatedAppSuaBimestresRoute: typeof AuthenticatedAppSuaBimestresRouteWithChildren
  AuthenticatedAppSuaImportarRoute: typeof AuthenticatedAppSuaImportarRoute
  AuthenticatedAppSuaMensualesRoute: typeof AuthenticatedAppSuaMensualesRouteWithChildren
  AuthenticatedAppSuaMovimientosRoute: typeof AuthenticatedAppSuaMovimientosRoute
  AuthenticatedAppSuaPagosRoute: typeof AuthenticatedAppSuaPagosRoute
  AuthenticatedAppSuaPatronesRoute: typeof AuthenticatedAppSuaPatronesRoute
  AuthenticatedAppSuaIndexRoute: typeof AuthenticatedAppSuaIndexRoute
}

const AuthenticatedAppSuaRouteChildren: AuthenticatedAppSuaRouteChildren = {
  AuthenticatedAppSuaBimestresRoute:
    AuthenticatedAppSuaBimestresRouteWithChildren,
  AuthenticatedAppSuaImportarRoute: AuthenticatedAppSuaImportarRoute,
  AuthenticatedAppSuaMensualesRoute:
    AuthenticatedAppSuaMensualesRouteWithChildren,
  AuthenticatedAppSuaMovimientosRoute: AuthenticatedAppSuaMovimientosRoute,
  AuthenticatedAppSuaPagosRoute: AuthenticatedAppSuaPagosRoute,
  AuthenticatedAppSuaPatronesRoute: AuthenticatedAppSuaPatronesRoute,
  AuthenticatedAppSuaIndexRoute: AuthenticatedAppSuaIndexRoute,
}

const AuthenticatedAppSuaRouteWithChildren =
  AuthenticatedAppSuaRoute._addFileChildren(AuthenticatedAppSuaRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedAppAsistenciasRoute: typeof AuthenticatedAppAsistenciasRoute
  AuthenticatedAppBalanceRoute: typeof AuthenticatedAppBalanceRoute
  AuthenticatedAppBalanzaRoute: typeof AuthenticatedAppBalanzaRoute
  AuthenticatedAppCobranzaRoute: typeof AuthenticatedAppCobranzaRoute
  AuthenticatedAppConfiguracionRoute: typeof AuthenticatedAppConfiguracionRoute
  AuthenticatedAppCuentasRoute: typeof AuthenticatedAppCuentasRoute
  AuthenticatedAppDeclaracionesRoute: typeof AuthenticatedAppDeclaracionesRoute
  AuthenticatedAppEmpleadosRoute: typeof AuthenticatedAppEmpleadosRoute
  AuthenticatedAppExportarRoute: typeof AuthenticatedAppExportarRoute
  AuthenticatedAppImportarRoute: typeof AuthenticatedAppImportarRoute
  AuthenticatedAppImportarLegacyRoute: typeof AuthenticatedAppImportarLegacyRoute
  AuthenticatedAppNominaRoute: typeof AuthenticatedAppNominaRoute
  AuthenticatedAppPolizasRoute: typeof AuthenticatedAppPolizasRoute
  AuthenticatedAppResultadosRoute: typeof AuthenticatedAppResultadosRoute
  AuthenticatedAppSuaRoute: typeof AuthenticatedAppSuaRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppFacturacionClientesRoute: typeof AuthenticatedAppFacturacionClientesRoute
  AuthenticatedAppFacturacionComplementosRoute: typeof AuthenticatedAppFacturacionComplementosRoute
  AuthenticatedAppFacturacionConfiguracionRoute: typeof AuthenticatedAppFacturacionConfiguracionRoute
  AuthenticatedAppFacturacionFacturasRoute: typeof AuthenticatedAppFacturacionFacturasRoute
  AuthenticatedAppFacturacionProductosRoute: typeof AuthenticatedAppFacturacionProductosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedAppAsistenciasRoute: AuthenticatedAppAsistenciasRoute,
  AuthenticatedAppBalanceRoute: AuthenticatedAppBalanceRoute,
  AuthenticatedAppBalanzaRoute: AuthenticatedAppBalanzaRoute,
  AuthenticatedAppCobranzaRoute: AuthenticatedAppCobranzaRoute,
  AuthenticatedAppConfiguracionRoute: AuthenticatedAppConfiguracionRoute,
  AuthenticatedAppCuentasRoute: AuthenticatedAppCuentasRoute,
  AuthenticatedAppDeclaracionesRoute: AuthenticatedAppDeclaracionesRoute,
  AuthenticatedAppEmpleadosRoute: AuthenticatedAppEmpleadosRoute,
  AuthenticatedAppExportarRoute: AuthenticatedAppExportarRoute,
  AuthenticatedAppImportarRoute: AuthenticatedAppImportarRoute,
  AuthenticatedAppImportarLegacyRoute: AuthenticatedAppImportarLegacyRoute,
  AuthenticatedAppNominaRoute: AuthenticatedAppNominaRoute,
  AuthenticatedAppPolizasRoute: AuthenticatedAppPolizasRoute,
  AuthenticatedAppResultadosRoute: AuthenticatedAppResultadosRoute,
  AuthenticatedAppSuaRoute: AuthenticatedAppSuaRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppFacturacionClientesRoute:
    AuthenticatedAppFacturacionClientesRoute,
  AuthenticatedAppFacturacionComplementosRoute:
    AuthenticatedAppFacturacionComplementosRoute,
  AuthenticatedAppFacturacionConfiguracionRoute:
    AuthenticatedAppFacturacionConfiguracionRoute,
  AuthenticatedAppFacturacionFacturasRoute:
    AuthenticatedAppFacturacionFacturasRoute,
  AuthenticatedAppFacturacionProductosRoute:
    AuthenticatedAppFacturacionProductosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
